/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yum_yumjni_JniTest */

#ifndef _Included_com_yum_yumjni_JniTest
#define _Included_com_yum_yumjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yum_yumjni_JniTest
 * Method:    calculate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_yum_yumjni_JniTest_calculate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
